service: PaymentGateway

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  profile: tue
  deploymentBucket:
    serverSideEncryption: AES256
    tags:
      key1: Pasarelas
      key2: Pagos
  deploymentPrefix: serverless.${self:service}
  tracing:
    lambda: true

functions:
  health:
    handler: app/health.handler
    events:
      - http:
          path: /
          method: get

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: yarn

